[2025-03-26T00:35:18.566+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T00:35:18.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T00:35:18.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T00:35:18.701+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T00:35:18.746+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_into_clickhouse> on 2025-03-25 00:00:00+00:00
[2025-03-26T00:35:18.770+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_clickhouse', 'load_into_clickhouse', 'scheduled__2025-03-25T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpyrot1p9z']
[2025-03-26T00:35:18.777+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_into_clickhouse
[2025-03-26T00:35:18.787+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T00:35:18.789+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2025-03-26T00:35:18.922+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse scheduled__2025-03-25T00:00:00+00:00 [running]> on host 372b19244b0d
[2025-03-26T00:35:19.271+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_into_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T00:00:00+00:00'
[2025-03-26T00:35:19.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T00:35:19.308+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T00:35:19.309+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 68, in load_into_clickhouse
    client = clickhouse_connect.get_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/__init__.py", line 122, in create_client
    return HttpClient(interface, host, port, username, password, database, access_token,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 161, in __init__
    super().__init__(database=database,
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 69, in __init__
    self._init_common_settings(apply_server_timezone)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 74, in _init_common_settings
    tuple(self.command('SELECT version(), timezone()', use_database=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 361, in command
    response = self._raw_request(payload, params, headers, method, fields=fields, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 474, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 395, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://clickhouse:9000 returned response code 400
[2025-03-26T00:35:19.328+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_s3_to_clickhouse, task_id=load_into_clickhouse, run_id=scheduled__2025-03-25T00:00:00+00:00, execution_date=20250325T000000, start_date=20250326T003518, end_date=20250326T003519
[2025-03-26T00:35:19.349+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task load_into_clickhouse (HTTPDriver for http://clickhouse:9000 returned response code 400; 193)
[2025-03-26T00:35:19.384+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-26T00:35:19.416+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T00:35:19.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
